package LexicalAnalyzer;

public enum TokenType {
    // Program
    SUGOD, KATAPUSAN,

    // Data Types : Keywords
    NUMERO, LETRA, TINUOD, TIPIK,
    // Keywords
    MUGNA, IPAKITA, DAWAT, KUNG, PUNDOK, WALA,ALANG,SA,PRINT,INPUT,

    // Literals
    NUMBER, CHARACTER, STRING, BOOLEAN_LITERAL,FLOAT, IDENTIFIER, KEYWORD, EXPRESSION,

    // Arithmetic Operators
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL, EQUALS, NOT_EQUALS,
    ADD_ASSIGN, SUB_ASSIGN, DIVIDE_ASSIGN, MULT_ASSIGN,
    OPERATION_ASSIGN, INCREMENT, DECREMENT,OPERATION,RELATIONAL_OPERATOR,LOGICAL_OPERATOR,
    // Logical Operators
    AND, OR, NOT,
    UG, O, DILI,

    // Boolean literals
    BOOL_TRUE, // "OO"
    BOOL_FALSE, // "DILI"

    //literals
    NULL,


    //Control Flow
    IF, ELSE_IF, ELSE , BLOCK,BLOCK_START, BLOCK_END, FOR,



    // Delimiters and Symbols
    LPAREN, RPAREN, AMPERSAND, DOLLAR,
    LBRACKET, RBRACKET, ASSIGNMENT, SEMICOLON,COLON, COMMA,SEPARATOR,
    LBRACE, RBRACE, CONCAT,NEXT_LINE,
    // Special
    COMMENT, EOF,
    UNKNOWN,START,END,




}